### ISSUE TITLE
Optional Artifactory publishing integration

### ISSUE THREAD

**Issue by jvmlet** [nebula-plugins/nebula-release-plugin#174]
Hello
Would you please make integration with Artifactory  publishing as _optional_ ?
We have 3 Artifactory  repositories : `snapshot`, `staging` (for RC builds) and `release`.
Each **non-final** build uploads artifacts to appropriate repository, but **final** build is allowed to be ran only for `vX.X.X-rc.#`  tag and  just moves the RC artifacts from `staging` to `release` repository while changing the name by removing `-rc.#` suffix.
This is the same approach implemented by Jenkins Artifactory release plugin.

Our  `gitlab-ci.yml` files looks like this

````
RC: 
  stage: release
  when: manual
  only:
    - master
  script:
    - ./gradlew  clean candidate

FINAL:
  stage: release
  when: manual
  only:
    - tags
  script:
    - ./gradlew  clean final
````
This approach ensures that release  is a **promotion** of RC - no commits in the middle and this is the same version that was deployed in SUT environment and manually/automatically tested 

Also it would be great to get the previous version of the project in addition to inferred .
Thanks
